### ISSUE TITLE
Advantage/Differences vs trpc

### ISSUE THREAD

**Issue by Mattrazol** [betwixt-labs/tempo#2]
What are the differences/advantages compared to trpc?

**Comment by AndrewMD5** [comment]
I’ve written about this on the wiki ([here](https://github.com/betwixt-labs/tempo/wiki/Design-Decisions#schemas--code-generation-vs-the-world) ), but to summarize - they’re different solutions to a similar problem. Importantly, Tempo is not limited to Typescript <-> Typescript communication. It will ultimately support RPC across language domains, so if you have a browser client and a Rust backend that use case is supported.

**Comment by Mattrazol** [comment]
I just read it now and I'm very curious on how Bebop works under the hood to guarantee runtime type checking in JavaScript.
Does it work similarly to Zod?
